spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_dev_user
    password: discodeit_dev_1234
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace