package com.sprint.mission.discodeit.exception;

public enum ErrorCode {
  //CHANNEL
  CHANNEL_NOT_FOUND,
  PRIVATE_CHANNEL_UPDATE, //PRIVATE채널은 업데이트 불가
  //MESSAGE
  MESSAGE_NOT_FOUND,
  //BINARY_CONTENT
  BINARY_CONTENT_NOT_FOUND,
  BINARY_CONTENT_STORAGE_FILE_NOT_FOUND,
  BINARY_CONTENT_SAME_FILE_EXISTS,
  //READ_STATUS
  READ_STATUS_NOT_FOUND,
  READ_STATUS_CREATE_FAILED,
  //USER
  USER_NOT_FOUND,
  USER_CREATE_FAILED,
  USER_ALREADY_EXISTS,
  //USER_STATUS
  USER_STATUS_NOT_FOUND,
  USER_STATUS_CREATE_FAILED,
}
